// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SpaceShipAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceshipAPI.Model.Ship.SpaceShip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("EngineLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShieldEnergy")
                        .HasColumnType("integer");

                    b.Property<int>("ShieldLevel")
                        .HasColumnType("integer");

                    b.Property<long?>("SpaceStationId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpaceStationId");

                    b.HasIndex("UserId");

                    b.ToTable("spaceship");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SpaceshipAPI.Spaceship.Model.Station.SpaceStation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("HangarLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StorageLevel")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("spacestation");
                });

            modelBuilder.Entity("SpaceshipAPI.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("StoredResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<long>("MinerShipId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SpaceStationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MinerShipId");

                    b.HasIndex("SpaceStationId");

                    b.ToTable("StoredResources");
                });

            modelBuilder.Entity("SpaceShipAPI.Model.Ship.MinerShip", b =>
                {
                    b.HasBaseType("SpaceshipAPI.Model.Ship.SpaceShip");

                    b.Property<int>("DrillLevel")
                        .HasColumnType("integer");

                    b.Property<int>("StorageLevel")
                        .HasColumnType("integer");

                    b.ToTable("minership");
                });

            modelBuilder.Entity("SpaceShipAPI.Model.Ship.ScoutShip", b =>
                {
                    b.HasBaseType("SpaceshipAPI.Model.Ship.SpaceShip");

                    b.Property<int>("ScannerLevel")
                        .HasColumnType("integer");

                    b.ToTable("scoutship");
                });

            modelBuilder.Entity("SpaceshipAPI.Model.Ship.SpaceShip", b =>
                {
                    b.HasOne("SpaceshipAPI.Spaceship.Model.Station.SpaceStation", "SpaceStation")
                        .WithMany("Hangar")
                        .HasForeignKey("SpaceStationId");

                    b.HasOne("SpaceshipAPI.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SpaceStation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpaceshipAPI.Spaceship.Model.Station.SpaceStation", b =>
                {
                    b.HasOne("SpaceshipAPI.UserEntity", "User")
                        .WithOne("SpaceStation")
                        .HasForeignKey("SpaceshipAPI.Spaceship.Model.Station.SpaceStation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoredResource", b =>
                {
                    b.HasOne("SpaceShipAPI.Model.Ship.MinerShip", "MinerShip")
                        .WithMany("StoredResources")
                        .HasForeignKey("MinerShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceshipAPI.Spaceship.Model.Station.SpaceStation", "SpaceStation")
                        .WithMany("StoredResources")
                        .HasForeignKey("SpaceStationId");

                    b.Navigation("MinerShip");

                    b.Navigation("SpaceStation");
                });

            modelBuilder.Entity("SpaceShipAPI.Model.Ship.MinerShip", b =>
                {
                    b.HasOne("SpaceshipAPI.Model.Ship.SpaceShip", null)
                        .WithOne()
                        .HasForeignKey("SpaceShipAPI.Model.Ship.MinerShip", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceShipAPI.Model.Ship.ScoutShip", b =>
                {
                    b.HasOne("SpaceshipAPI.Model.Ship.SpaceShip", null)
                        .WithOne()
                        .HasForeignKey("SpaceShipAPI.Model.Ship.ScoutShip", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceshipAPI.Spaceship.Model.Station.SpaceStation", b =>
                {
                    b.Navigation("Hangar");

                    b.Navigation("StoredResources");
                });

            modelBuilder.Entity("SpaceshipAPI.UserEntity", b =>
                {
                    b.Navigation("SpaceStation")
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceShipAPI.Model.Ship.MinerShip", b =>
                {
                    b.Navigation("StoredResources");
                });
#pragma warning restore 612, 618
        }
    }
}
